# Generated by Django 4.2.1 on 2023-06-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitools',
            name='img',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
