# Generated by Django 4.2.1 on 2023-06-22 01:37

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_aitools_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitools',
            name='link',
            field=models.CharField(max_length=200, validators=[webapp.models.validate_https_url]),
        ),
    ]
