# Generated by Django 4.2.4 on 2023-09-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
