# Generated by Django 4.2.4 on 2023-09-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitools',
            name='user',
            field=models.CharField(default='utkarsh6', max_length=200),
        ),
    ]
