# Generated by Django 4.2.4 on 2023-09-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_aitools_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitools',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
